#!/bin/bash

# Check if two arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <path_to_markdown_file> <path_to_output_pdf>"
    exit 1
fi

# Arguments
MARKDOWN_FILE=$1
OUTPUT_PDF=$2

# Set up directories and file names
WORKDIR=$(mktemp -d)            # Temporary directory to mount to the container
INPUT_MD="$WORKDIR/input.md"     # Renamed markdown file
OUTPUT_CONTAINER_PDF="$WORKDIR/output.pdf" # PDF generated by the container

# Copy and rename the markdown file
cp "$MARKDOWN_FILE" "$INPUT_MD"

# Run the Docker container, mounting the temporary directory
# Note that we are assuming that we will use the default template that is inside 
# the container.
docker run --rm -v "$WORKDIR":/data resistor52/md2pdf /data/input.md \
    /app/template.tex /data/output.pdf

# Check if the PDF was created
if [ -f "$OUTPUT_CONTAINER_PDF" ]; then
    # Copy the generated PDF to the specified output location
    cp "$OUTPUT_CONTAINER_PDF" "$OUTPUT_PDF"
    echo "PDF generated successfully: $OUTPUT_PDF"
else
    echo "Error: PDF was not generated."
fi

# Clean up the temporary directory
rm -rf "$WORKDIR"
